# Site settings
name: Ted.62
description: "Simple Home"
url: "http://62tae.github.io/"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  62tae
facebook_username: kitae.you
twitter_username: 62tae
google_plus_username: 62tae
linkedin_username: TED.62
instagram_username:  62tae
flickr_username: youkitae62
blog_url: "/blog"
email: youkitae62@gmail.com


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars0.githubusercontent.com/u/10955469?v=3&s=460"


front_img: yes
#front_img_path: "imgs/background.jpg"
front_img_path: "https://c1.staticflickr.com/8/7433/26606326504_3ad47581f8_k.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
